# -*- coding: utf-8 -*-
"""winapp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLkMBqEcYu9kGdH7GQN7AHa24ml_MEOH
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
sns.set(style='dark')

all_df = pd.read_csv("all_data.csv")

# Convert 'shipping_limit_date' to datetime format for easier plotting
data['shipping_limit_date'] = pd.to_datetime(data['shipping_limit_date'])

# Streamlit app setup
st.title('Price and Freight Value Over Time')

# Line plot: Price and Freight Value Over Time
fig, ax = plt.subplots()
ax.plot(data['shipping_limit_date'], data['price'], label='Price', color='green', alpha=0.6)
ax.plot(data['shipping_limit_date'], data['freight_value'], label='Freight Value', color='red', alpha=0.6)
ax.set_title('Price and Freight Value Over Time')
ax.set_xlabel('Shipping Limit Date')
ax.set_ylabel('Value (in currency)')
ax.legend()

# Display the plot in Streamlit
st.pyplot(fig)
